[project]
name = "bt-port-redirector"
version = "0.1.0"
description = "Modify the port reported to Tracker in real time"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]
