[project]
name = "bt-port-redirector"
version = "0.1.0"
description = "Modify the port reported to Tracker in real time"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "mitmproxy>=11.1.3",
    "uvicorn[standard]>=0.34.0",
]
